services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: LocalDev123
      POSTGRES_USER: postgres
      POSTGRES_DB: playground
